// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'community-wrap': string;
  communityWrap: string;
  'info-item': string;
  infoItem: string;
  'item-content': string;
  'item-title': string;
  itemContent: string;
  itemTitle: string;
  'pop-close': string;
  'pop-title': string;
  popClose: string;
  popTitle: string;
}
declare var cssExports: CssExports;
export = cssExports;
