// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'community-wrap': string;
  communityWrap: string;
  'info-item': string;
  infoItem: string;
  'item-content': string;
  'item-content-link': string;
  'item-detail': string;
  'item-title': string;
  itemContent: string;
  itemContentLink: string;
  itemDetail: string;
  itemTitle: string;
  'legend-item-circle': string;
  legendItemCircle: string;
  'pop-close': string;
  'pop-title': string;
  popClose: string;
  popTitle: string;
  'wrap-point': string;
  wrapPoint: string;
}
declare var cssExports: CssExports;
export = cssExports;
