// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'car-item': string;
  'car-list': string;
  carItem: string;
  carList: string;
  cctv: string;
  content: string;
  footer: string;
  icon: string;
  insiCode: string;
  label: string;
  macCode: string;
  machine: string;
  offline: string;
  online: string;
  plot: string;
  'pop-close': string;
  'pop-guide': string;
  popClose: string;
  popGuide: string;
  popup: string;
  title: string;
  type10: string;
  type20: string;
  'video-close': string;
  'video-title': string;
  'video-top': string;
  videoClose: string;
  videoTitle: string;
  videoTop: string;
  videodoor: string;
}
declare var cssExports: CssExports;
export = cssExports;
